#lang racket

(require rackunit/text-ui)
(require racket/date)

(require racket/runtime-path)
(define-runtime-path workbook_xml_file "workbook.xml")

(require rackunit "../../main.rkt")

(define test-xml
  (test-suite
   "test-workbook"

   (test-case
    "test-workbook"

    (let ([xml_hash (xml->hash workbook_xml_file)])
      (check-equal? (hash-ref xml_hash "workbook's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.xmlns") "http://schemas.openxmlformats.org/spreadsheetml/2006/main")
      (check-equal? (hash-ref xml_hash "workbook.xmlns:r") "http://schemas.openxmlformats.org/officeDocument/2006/relationships")
      (check-equal? (hash-ref xml_hash "workbook.fileVersion's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.fileVersion") "")
      (check-equal? (hash-ref xml_hash "workbook.fileVersion.appName") "xl")
      (check-equal? (hash-ref xml_hash "workbook.fileVersion.lastEdited") "4")
      (check-equal? (hash-ref xml_hash "workbook.fileVersion.lowestEdited") "4")
      (check-equal? (hash-ref xml_hash "workbook.fileVersion.rupBuild") "4505")
      (check-equal? (hash-ref xml_hash "workbook.workbookPr's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.workbookPr") "")
      (check-equal? (hash-ref xml_hash "workbook.workbookPr.filterPrivacy") "1")
      (check-equal? (hash-ref xml_hash "workbook.workbookPr.defaultThemeVersion") "124226")
      (check-equal? (hash-ref xml_hash "workbook.bookViews's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.bookViews.workbookView's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.bookViews.workbookView") "")
      (check-equal? (hash-ref xml_hash "workbook.bookViews.workbookView.xWindow") "0")
      (check-equal? (hash-ref xml_hash "workbook.bookViews.workbookView.yWindow") "90")
      (check-equal? (hash-ref xml_hash "workbook.bookViews.workbookView.windowWidth") "19200")
      (check-equal? (hash-ref xml_hash "workbook.bookViews.workbookView.windowHeight") "10590")
      (check-equal? (hash-ref xml_hash "workbook.calcPr's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.calcPr") "")
      (check-equal? (hash-ref xml_hash "workbook.calcPr.calcId") "124519")
      (check-equal? (hash-ref xml_hash "workbook.sheets's count") 1)
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet's count") 10)
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet1") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet1.name") "DataSheet")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet1.sheetId") "1")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet1.r:id") "rId1")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet2") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet2.name") "DataSheetWithStyle")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet2.sheetId") "2")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet2.r:id") "rId2")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet3") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet3.name") "DataSheetWithStyle2")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet3.sheetId") "3")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet3.r:id") "rId3")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet4") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet4.name") "LineChart1")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet4.sheetId") "4")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet4.r:id") "rId4")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet5") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet5.name") "LineChart2")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet5.sheetId") "5")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet5.r:id") "rId5")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet6") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet6.name") "LineChart3D")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet6.sheetId") "6")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet6.r:id") "rId6")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet7") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet7.name") "BarChart")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet7.sheetId") "7")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet7.r:id") "rId7")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet8") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet8.name") "BarChart3D")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet8.sheetId") "8")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet8.r:id") "rId8")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet9") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet9.name") "PieChart")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet9.sheetId") "9")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet9.r:id") "rId9")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet10") "")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet10.name") "PieChart3D")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet10.sheetId") "10")
      (check-equal? (hash-ref xml_hash "workbook.sheets.sheet10.r:id") "rId10")

      (check-equal? (hash-count xml_hash) 65)
      )

    )

  ))

(run-tests test-xml)
